# Generated by Django 2.2.2 on 2020-08-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0011_auto_20200812_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewHotArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('orders', models.IntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='newhotarticle', to='article.Article', to_field='inner_link', verbose_name='文章图片')),
            ],
            options={
                'verbose_name': '新热榜文章',
                'verbose_name_plural': '新热榜文章',
                'db_table': 'newhotarticle',
            },
        ),
    ]
