# Generated by Django 2.2.2 on 2020-08-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newhotsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newhotarticle',
            table='nineth_newhotarticle',
        ),
    ]
