# Generated by Django 2.2.2 on 2020-08-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='nineth_article',
        ),
    ]
