# Generated by Django 2.2.2 on 2020-08-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200810_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
        migrations.AlterModelOptions(
            name='up',
            options={'verbose_name': '文章点赞', 'verbose_name_plural': '文章点赞'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='nineth_article_comment',
        ),
        migrations.AlterModelTable(
            name='up',
            table='nineth_article_up',
        ),
    ]
