# Generated by Django 2.2.2 on 2020-08-11 18:11

import article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200810_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_imgs',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='article/article_img', verbose_name='文章图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='show_img',
            field=models.ImageField(blank=True, max_length=1, null=True, upload_to='article/show_img', verbose_name='封面图片'),
        ),
        migrations.CreateModel(
            name='ArticleImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('orders', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='文章图片')),
                ('img', models.ImageField(upload_to=article.models.upload_to)),
                ('article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.Article', verbose_name='文章图片')),
            ],
            options={
                'verbose_name': '文章图片',
                'verbose_name_plural': '文章图片',
                'db_table': 'nineth_article_img',
            },
        ),
    ]
