# Generated by Django 2.2.2 on 2020-08-11 18:54

import article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200811_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='inner_link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='文章详情链接'),
        ),
        migrations.AlterField(
            model_name='articleimg',
            name='article',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.Article', to_field='inner_link', verbose_name='文章图片'),
        ),
        migrations.AlterField(
            model_name='articleimg',
            name='img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=article.models.upload_to, verbose_name='文章图片'),
        ),
    ]
