# Generated by Django 2.2.2 on 2020-08-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200811_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='article.Article', to_field='inner_link'),
        ),
        migrations.AlterField(
            model_name='up',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.Article', to_field='inner_link'),
        ),
    ]
