# Generated by Django 2.2.2 on 2020-08-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200812_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleimg',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='up',
            name='orders',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
