# Generated by Django 2.2.2 on 2020-08-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200812_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='show_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='article/show_img', verbose_name='封面图片'),
        ),
    ]
