# Generated by Django 2.2.2 on 2020-08-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200812_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimg',
            name='article',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='img', to='article.Article', to_field='inner_link', verbose_name='文章图片'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='article.Article', to_field='inner_link'),
        ),
    ]
